spring.application.name=truck

# MySql setting
#spring.datasource.url=jdbc:mysql://localhost:3306/cmc_c2c_local?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
spring.datasource.url=jdbc:mysql://localhost:3306/truck?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=root

# mongoDB setting
spring.data.mongodb.uri=mongodb://localhost:27017/admin
spring.data.mongodb.database=cmc_c2c

# Redis setting
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=6

# stream setting
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# mail setting
spring.mail.username=hsiang3344cus@gmail.com
spring.mail.password=jerarhqtzetbtvsm

# freemarker
spring.freemarker.cache=false

# tracing
management.tracing.enabled=true

# project env
# platform
env.platform.profile=local
env.platform.code=coinFare
env.platform.en-name=coinFare
env.platform.tw-name=coinFare
env.platform.cn-name=coinFare
env.platform.backstage.url=https://dev.coinfare.net
# internal API
env.internal-api.rpc-client=http://localhost:8001/rpc/
env.internal-api.api-center=http://localhost:8001/rpc/
env.internal-api.data-center=http://localhost:8001/rpc/
# google storage setting
env.gcp-storage.bucket=coinfare-dev-backend-image
env.gcp-storage.token=upload/coinfare-618fd566fc1e.json
env.gcp-storage.encryption-key=pQnMtr8btBunRXNbjZA+QXlaDC2tqd5gchZLp8sIkyA=
env.gcp-storage.image-url=
# switch config
wanda.switch.need-encrypt=false
env.switch.websocket-listener=false
env.switch.scheduler=false
# amount
env.amount.scale=18
env.amount.rounding-mode=1
# sms
# twilio
env.sms.twilio.url=
env.sms.twilio.auth-token=
env.sms.twilio.sid=
env.sms.twilio.messageing-service-sid=
#aws
env.sms.aws.accesskey=
env.sms.aws.secretkey=
env.sms.aws.regions=
#aliyun
env.sms.aliyun.accessKeyId=
env.sms.aliyun.accessKeySecret=
env.sms.aliyun.endpoint=
# push
env.push-notice.api-token=



