package com.luzhu.truck.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum SystemExceptionEnum implements IRuntimeExceptionEnum{
    PARAM_ERROR("SYS_0001", "PARAM_ERROR", "參數錯誤"),
    INSERT_ERROR("SYS_0002", "INSERT_ERROR", "新增失敗"),
    UPDATE_ERROR("SYS_0003", "UPDATE_ERROR", "修改失敗"),
    DELETE_ERROR("SYS_0004", "DELETE_ERROR", "刪除失敗"),
    DATA_ERROR("SYS_0005", "DATA_ERROR", "資料錯誤"),
    NO_DATA("SYS_0006", "NO_DATA", "查無資料"),
    DUPLICATE_DATA("SYS_0007", "DUPLICATE_DATA", "資料重覆"),
    PRIMARY_KEY_CONFLICT("SYS_0008", "保險卡號重覆", "PRIMARY_KEY_CONFLICT"),
    CAR_AGENCY_NAME_DUPLICATE("SYS_0009", "車行名稱重覆", "PRIMARY_KEY_CONFLICT"),
    INVOICE_DISABLE("SYS_0010", "發票已作廢, 無法更新", "INVOICE_DISABLE"),
    INVOICE_ALREADY_REBILLED("SYS_0016", "發票已報廢轉月，無法重複操作", "INVOICE_ALREADY_REBILLED"),
    INVOICE_ADJUSTMENT_NO_REBILL("SYS_0017", "調整列不可再報廢轉月", "INVOICE_ADJUSTMENT_NO_REBILL"),
    LEND_MONEY_DISABLE("SYS_0018", "借款已作廢, 無法更新", "LEND_MONEY_DISABLE"),
    LEND_MONEY_ALREADY_REBILLED("SYS_0019", "借款已報廢轉月，無法重複操作", "LEND_MONEY_ALREADY_REBILLED"),
    LEND_MONEY_ADJUSTMENT_NO_REBILL("SYS_0020", "借款調整列不可再報廢轉月", "LEND_MONEY_ADJUSTMENT_NO_REBILL"),
    GIVE_BACK_MONEY_DISABLE("SYS_0021", "入款已作廢, 無法更新", "GIVE_BACK_MONEY_DISABLE"),
    GIVE_BACK_MONEY_ALREADY_REBILLED("SYS_0022", "入款已報廢轉月，無法重複操作", "GIVE_BACK_MONEY_ALREADY_REBILLED"),
    GIVE_BACK_MONEY_ADJUSTMENT_NO_REBILL("SYS_0023", "入款調整列不可再報廢轉月", "GIVE_BACK_MONEY_ADJUSTMENT_NO_REBILL"),
    OTHER_LEND_MONEY_DISABLE("SYS_0024", "其他應收已作廢, 無法更新", "OTHER_LEND_MONEY_DISABLE"),
    OTHER_LEND_MONEY_ALREADY_REBILLED("SYS_0025", "其他應收已報廢轉月，無法重複操作", "OTHER_LEND_MONEY_ALREADY_REBILLED"),
    OTHER_LEND_MONEY_ADJUSTMENT_NO_REBILL("SYS_0026", "其他應收調整列不可再報廢轉月", "OTHER_LEND_MONEY_ADJUSTMENT_NO_REBILL"),
    OTHER_GIVE_BACK_MONEY_DISABLE("SYS_0027", "其他抵收已作廢, 無法更新", "OTHER_GIVE_BACK_MONEY_DISABLE"),
    OTHER_GIVE_BACK_MONEY_ALREADY_REBILLED("SYS_0028", "其他抵收已報廢轉月，無法重複操作", "OTHER_GIVE_BACK_MONEY_ALREADY_REBILLED"),
    OTHER_GIVE_BACK_MONEY_ADJUSTMENT_NO_REBILL("SYS_0029", "其他抵收調整列不可再報廢轉月", "OTHER_GIVE_BACK_MONEY_ADJUSTMENT_NO_REBILL"),
    PAY_INTEREST_DISABLE("SYS_0030", "代支利息已作廢, 無法更新", "PAY_INTEREST_DISABLE"),
    PAY_INTEREST_ALREADY_REBILLED("SYS_0031", "代支利息已報廢轉月，無法重複操作", "PAY_INTEREST_ALREADY_REBILLED"),
    PAY_INTEREST_ADJUSTMENT_NO_REBILL("SYS_0032", "代支利息調整列不可再報廢轉月", "PAY_INTEREST_ADJUSTMENT_NO_REBILL"),
    GENERATE_CURRENT_BILL("SYS_0011", "不可重複產出當月帳單", "CANT_GENERATE_CURRENT_BILL_FOR_MANY_TIME"),
    DUPLICATE_CAR_LICENSE_NUM("SYS_0012", "車牌重複", "DUPLICATE_CAR_LICENSE_NUM"),
    END_DATE_EARLY_THAN_START_DATE("SYS_0013", "結束日不可早於起始日", "END_DATE_EARLY_THAN_START_DATE"),
    NEED_SET_INSURANCE_CAR_FEE("SYS_0014", "管費或保單尚未設定", "NEED_SET_INSURANCE_CAR_FEE"),
    DUPLICATE_ENABLED_LOAN_FEE_SETTING("SYS_0015", "該車輛已有啟用的車貸設定,若要新增車貸,請先將舊有車貸失效", "DUPLICATE_ENABLED_LOAN_FEE_SETTING"),

    NOT_IMPLEMENTED_METHOD("SYS_8888", "NOT_IMPLEMENTED_METHOD", "未實作方法"),

    SYSTEM_ERROR("SYS_9999", "UNKNOWN_FATAL_ERROR", "系統錯誤"),
    ;

    private String code;
    private String message;
    private String memo;

}
